netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_001 remoteip= 50.22.78.28
netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_002 remoteip= 169.55.40.5
netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_003 remoteip= 169.55.0.227
netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_004 remoteip= 69.41.163.149
netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_005 remoteip= 50.97.82.44
netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_006 remoteip= 174.127.73.85
netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_007 remoteip= 50.22.78.29
netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_008 remoteip= 185.80.221.19
netsh advfirewall firewall add rule program="c:\Program Files (x86)\Internet Download Manager\IDMan.exe" dir=out action=block name=idm_out_009 remoteip= 169.55.0.224
